# Info - Planning Groups
# -------------------------------
# Description:
#   Message-type for containing information on robot planning groups parameter data
#
# Version:
#   0.1 -   Initial version
#           [19.11.2023] - Jan T. Olsen
# -------------------------------

# Planning frames parameter data
string robot            # Common robot planning-group
string robot_eoat       # Robot with end-effector planning-group