# Info - Joint Limit
# -------------------------------
# Description:
#   Message-type for containing information on joint limits parameter data
#
# Version:
#   0.1 -   Initial version
#           [19.11.2023] - Jan T. Olsen
# -------------------------------

# Joint limit parameter data
info_msgs/InfoLimit position        # Joint position limits
info_msgs/InfoLimit velocity        # Joint velocity limits
info_msgs/InfoLimit acceleration    # Joint acceleration limits 
info_msgs/InfoLimit torque          # Joint torque limits