# Info - Limit
# -------------------------------
# Description:
#   Message-type for containing information on limits parameter data
#
# Version:
#   0.1 -   Initial version
#           [19.11.2023] - Jan T. Olsen
# -------------------------------

# Limit parameter data
float64 limit       # Common limit value (when min-/max-limit value is not applicable)
float64 limit_min   # Minimum limit value
float64 limit_max   # Maximum limit value