# Info - External Axis
# -------------------------------
# Description:
#   Message-type for info external-axis data
#
# Version:
#   0.1 -   Initial version
#           [14.01.2024] - Jan T. Olsen
# -------------------------------

# Exteterna Axis Type constants
int32 ROTATION  = 0
int32 LINEAR    = 1

# Identifier for determining axis-type 
# [ROTATION [0], LINEAR [1]]
int32 type
string type_name
